# Generated by Django 4.2.7 on 2025-03-07 20:18

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=django_summernote.fields.SummernoteTextField(default=''),
            preserve_default=False,
        ),
    ]
